export type ObjectiveReview = {
  scenarios: Array<[clue: string, move: string, why: string]>;
  traps: Array<[temptation: string, correction: string]>;
  sources?: Array<[label: string, url: string]>;
};

const AGENTS = 'https://www.anthropic.com/engineering/building-effective-agents';
const TOOLS = 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/how-tool-use-works';
const TOOL_CONTEXT = 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/manage-tool-context';
const MODELS = 'https://platform.claude.com/docs/en/docs/about-claude/models/choosing-a-model';
const PROMPTING = 'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices';
const CONTEXT = 'https://platform.claude.com/docs/en/build-with-claude/context-windows';
const CACHE = 'https://platform.claude.com/docs/en/build-with-claude/prompt-caching';
const EVALS = 'https://platform.claude.com/docs/en/test-and-evaluate/develop-tests';
const MCP = 'https://platform.claude.com/docs/en/agents-and-tools/mcp-connector';
const COST = 'https://platform.claude.com/docs/en/about-claude/models/optimizing-for-cost-and-intelligence';
const USAGE = 'https://platform.claude.com/docs/en/manage-claude/usage-cost-api';
const CODE_CONFIG = 'https://code.claude.com/docs/en/configuration';
const CODE_PERMISSIONS = 'https://code.claude.com/docs/en/permissions';
const CODE_SANDBOX = 'https://code.claude.com/docs/en/sandboxing';
const CODE_AGENTS = 'https://code.claude.com/docs/en/agents';

export const OBJECTIVE_REVIEWS: Record<string, ObjectiveReview> = {
  '1.1': { scenarios: [['A stakeholder asks for “a chatbot”', 'Reframe the job', 'The interface is not the business outcome.'], ['Work is language-heavy but fully deterministic', 'Keep deterministic code', 'Claude should handle ambiguity, not replace reliable rules.'], ['A useful answer cannot be measured', 'Define acceptance first', 'Architecture cannot compensate for an undefined target.']], traps: [['Starting with an agent', 'Start with the user, workflow, baseline, and success measure.'], ['Automating the whole job', 'Find the bounded language or reasoning step where Claude adds value.']], sources: [['Define success criteria', EVALS]] },
  '1.2': { scenarios: [['The answer depends on private documents', 'Add retrieval and citations', 'Evidence must enter before generation.'], ['The system can change a record', 'Add validation and an action gate', 'Side effects need a stronger boundary than prose.'], ['Quality may drift after launch', 'Close the feedback loop', 'Production outcomes must feed monitoring and evals.']], traps: [['Drawing only the happy path', 'Show timeouts, refusals, fallbacks, retries, and ownership.'], ['Treating Claude as the whole system', 'Separate model behavior from application, data, and policy controls.']], sources: [['Tool-use contract', TOOLS], ['Define success criteria', EVALS]] },
  '1.3': { scenarios: [['The steps and branches are known', 'Workflow', 'Code should own deterministic routing.'], ['The task must choose its own path and tools', 'Agent', 'Runtime uncertainty justifies model-controlled loops.'], ['Claude needs fresh facts but no autonomy', 'Augmented LLM', 'Retrieval or one tool call may be enough.']], traps: [['Using “agent” as a synonym for any LLM app', 'Autonomy means Claude controls some sequence of actions.'], ['Choosing the most flexible pattern', 'Flexibility adds latency, cost, and failure modes.']], sources: [['Building effective agents', AGENTS], ['How tool use works', TOOLS]] },
  '1.4': { scenarios: [['Subtasks are independent and known', 'Parallel workers', 'Concurrency lowers elapsed time without dynamic planning.'], ['The subtasks emerge during investigation', 'Orchestrator-workers', 'A coordinator can create and re-plan work at runtime.'], ['A draft improves through critique', 'Evaluator-optimizer', 'The feedback loop has an explicit quality role.'], ['Specialists must debate or share discoveries', 'Peer-capable team', 'Direct communication may justify the extra coordination cost.']], traps: [['Splitting tightly coupled work', 'Shared context and dependencies erase the benefit of separate agents.'], ['Giving every worker every tool', 'Assign role-specific context and least-privilege capabilities.'], ['No budget or stop condition', 'Bound fan-out, turns, retries, time, and spend before execution.']], sources: [['Building effective agents', AGENTS], ['Claude Code parallel agents', CODE_AGENTS]] },
  '1.5': { scenarios: [['Several outputs share no dependency', 'Parallelize', 'They can run concurrently and combine later.'], ['Each step consumes the prior result', 'Prompt chain or pipeline', 'The dependency determines order.'], ['The task graph is unknown until evidence arrives', 'Dynamic orchestration', 'The system must revise the plan at runtime.']], traps: [['Splitting by equal prompt size', 'Decompose around responsibility and interfaces.'], ['Returning prose from every subtask', 'Prefer checkable outputs with explicit schemas or artifacts.']], sources: [['Building effective agents', AGENTS]] },
  '1.6': { scenarios: [['The goal is faster case handling', 'Efficiency metric', 'Measure time or effort removed.'], ['The same experts should handle more work', 'Productivity metric', 'Measure useful throughput, not model calls.'], ['A new service becomes possible', 'Transformation metric', 'Measure adoption and realized capability.']], traps: [['Reporting token savings as business value', 'Connect technical cost to unit economics or an SLA.'], ['Ignoring the quality floor', 'Savings that break acceptance criteria destroy value.']], sources: [['Define success criteria', EVALS], ['Cost and intelligence', COST]] },

  '2.1': { scenarios: [['High-volume classification with a clear rubric', 'Start efficiency-first', 'A faster model may clear the quality bar at lower unit cost.'], ['Long-horizon planning with costly errors', 'Start capability-first', 'Reasoning quality dominates latency and price.'], ['One model succeeds except on hard cases', 'Route or escalate', 'A mixed strategy can improve cost per success.']], traps: [['Selecting from list price alone', 'Retries and failures may make the cheap model expensive.'], ['Always choosing the newest or largest model', 'Evaluate the actual task and deployment constraints.']], sources: [['Choosing the right model', MODELS], ['Models overview', 'https://platform.claude.com/docs/en/models/overview']] },
  '2.2': { scenarios: [['The output must follow a stable format', 'State a clear contract and validate it', 'Prompting improves behavior; schemas enforce structure.'], ['The prompt mixes rules, examples, and documents', 'Use labeled structure', 'Explicit sections reduce instruction ambiguity.'], ['The user requests a forbidden action', 'Enforce outside the prompt', 'Authorization cannot depend on model obedience.']], traps: [['Putting secrets in the system prompt', 'Prompts are context, not a secret store.'], ['Calling every safety rule a guardrail', 'Distinguish behavioral guidance from hard controls.']], sources: [['Prompting best practices', PROMPTING], ['Tool use', TOOLS]] },
  '2.3': { scenarios: [['The task is familiar and requirements are clear', 'Zero-shot', 'Avoid examples until evidence shows they are needed.'], ['The boundary is subtle or stylistic', 'Few-shot', 'Examples demonstrate the intended decision surface.'], ['A complex answer has separable parts', 'Decompose', 'Intermediate checks reduce compounding error.']], traps: [['Using chain-of-thought as a magic phrase', 'Use current thinking controls and evaluate results; do not demand exposed private reasoning.'], ['Adding many near-identical examples', 'Diverse examples teach the boundary better and consume less context.']], sources: [['Prompting best practices', PROMPTING], ['Thinking', 'https://platform.claude.com/docs/en/about-claude/models/extended-thinking-models']] },
  '2.4': { scenarios: [['Long conversations approach the limit', 'Compact or summarize', 'History grows every turn and context quality can decay.'], ['Large static documents repeat', 'Cache or retrieve', 'Re-sending everything wastes tokens and attention.'], ['Tool results dominate the window', 'Reduce result payloads', 'Return only fields needed for the next step.']], traps: [['Assuming more context always improves recall', 'Long context can suffer context rot; curate it.'], ['Counting only user messages', 'System text, tools, results, images, thinking, and output all count.']], sources: [['Context windows', CONTEXT], ['Manage tool context', TOOL_CONTEXT]] },
  '2.5': { scenarios: [['The prefix repeats exactly across requests', 'Prompt caching', 'Identical stable content can be reused.'], ['A procedure and resources recur across tasks', 'Skill', 'Package reusable instructions and supporting material.'], ['Teams share a prompt pattern with variable fields', 'Template or module', 'Separate the contract from request data.']], traps: [['Putting a timestamp before the cache breakpoint', 'Any change breaks an exact-prefix cache hit.'], ['Caching content that is rarely reused', 'Cache writes have a premium; measure reuse.']], sources: [['Prompt caching', CACHE], ['Prompting best practices', PROMPTING]] },

  '3.1': { scenarios: [['A role never uses destructive tools', 'Remove them', 'Elimination beats monitoring an unnecessary privilege.'], ['A catalog has dozens of rare tools', 'Progressive discovery', 'Do not load the full schema surface every turn.'], ['Several tools differ only by verb', 'Consolidate carefully', 'A coherent action schema reduces selection confusion.']], traps: [['Keeping tools “just in case”', 'Unused capability still consumes context and expands attack surface.'], ['Adding warnings around unnecessary tools', 'Guarding is weaker than removing.']], sources: [['Manage tool context', TOOL_CONTEXT], ['Tool use', TOOLS]] },
  '3.2': { scenarios: [['Many users share one backend credential', 'Preserve user identity and re-authorize', 'A service identity can become a confused deputy.'], ['An agent calls a sensitive tool', 'Use narrow delegated scope', 'The tool should receive only required authority.'], ['A request crosses multiple services', 'Propagate actor and trace identity', 'Audit needs an attributable chain.']], traps: [['Treating authentication as authorization', 'Knowing who called does not prove they may act.'], ['Passing a broad bearer token through every hop', 'Use scoped, short-lived credentials at the boundary.']], sources: [['MCP connector', MCP], ['MCP security', 'https://platform.claude.com/docs/en/agents-and-tools/mcp-tunnels/security']] },
  '3.3': { scenarios: [['The UI must feel interactive', 'Set a percentile latency budget', 'Average latency hides slow-tail experience.'], ['The output drives a high-impact decision', 'Spend latency for verified accuracy', 'The consequence changes the feasible trade-off.'], ['Easy and hard requests are mixed', 'Route by difficulty', 'One configuration need not serve every case.']], traps: [['Comparing model response time only', 'Measure retrieval, tools, queues, retries, and generation end to end.'], ['Picking a single winner without thresholds', 'Choose among configurations that satisfy the use case.']], sources: [['Choosing the right model', MODELS], ['Cost and intelligence', COST]] },
  '3.4': { scenarios: [['One user reports a strange failure', 'Inspect the trace', 'A trace reconstructs the individual path.'], ['Latency rises across a region', 'Inspect metrics', 'Aggregates reveal scope and trend.'], ['A tool returns malformed output', 'Inspect structured logs and payload metadata', 'The failure belongs at the tool boundary.']], traps: [['Logging full prompts by default', 'Minimize sensitive content and use governed sampling.'], ['Monitoring HTTP success only', 'A 200 response can still be a task failure.']], sources: [['Usage and Cost API', USAGE], ['Handle tool calls', 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/handle-tool-calls']] },
  '3.5': { scenarios: [['Answers depend on document sections', 'Chunk on semantic boundaries', 'Preserve the unit a useful answer needs.'], ['Exact codes and semantic questions coexist', 'Build hybrid indexes', 'Embeddings alone may miss identifiers.'], ['Documents change frequently', 'Version and incrementally re-index', 'Freshness becomes part of correctness.']], traps: [['Choosing chunk size from a generic recipe', 'Use query, answer, and citation granularity.'], ['Evaluating only final prose', 'Measure retrieval recall and ranking separately.']], sources: [['Contextual retrieval', 'https://www.anthropic.com/engineering/contextual-retrieval'], ['Define success criteria', EVALS]] },
  '3.6': { scenarios: [['The query contains an exact SKU or policy number', 'Lexical or structured retrieval', 'Exact matching is the strongest signal.'], ['The query paraphrases a concept', 'Vector retrieval', 'Semantic similarity bridges vocabulary.'], ['A broad result set needs precision', 'Rerank after retrieval', 'A second-stage judge can improve ordering.']], traps: [['Using vector search for every query', 'Match retrieval to data and query shape.'], ['Applying metadata filters after generation', 'Filter before evidence reaches the model.']], sources: [['Contextual retrieval', 'https://www.anthropic.com/engineering/contextual-retrieval']] },
  '3.7': { scenarios: [['Your app calls one stable service', 'Direct API', 'A bespoke integration is simple and explicit.'], ['Claude needs a reusable model-facing tool catalog', 'MCP', 'The protocol standardizes tools and resources.'], ['Independent agents own separate goals', 'A2A', 'Peer coordination differs from a tool call.'], ['A developer operates a local program', 'CLI', 'The shell interface may already be the correct boundary.']], traps: [['Choosing MCP because it is fashionable', 'Use it when discovery and model-facing reuse justify another protocol.'], ['Assuming the protocol supplies authorization', 'Identity and permission remain architecture responsibilities.']], sources: [['MCP connector', MCP], ['How tool use works', TOOLS]] },
  '3.8': { scenarios: [['Five stable tools serve nearly every request', 'Load them upfront', 'Discovery overhead buys little.'], ['Hundreds of tools vary by task', 'Tool search', 'Load only relevant definitions.'], ['Tool results accumulate across a long run', 'Programmatic calls or compaction', 'The pressure is results, not definitions.']], traps: [['Using discovery for a tiny stable catalog', 'The extra round trip adds needless latency and failure.'], ['Caching as a cure for context size', 'Caching lowers cost; cached tokens still count toward context.']], sources: [['Manage tool context', TOOL_CONTEXT]] },

  '4.1': { scenarios: [['Stakeholders say “accurate”', 'Define task-specific scoring and a threshold', 'The word alone cannot determine readiness.'], ['A system is correct but too slow', 'Add operational metrics', 'Quality is only one release constraint.'], ['Average quality hides a weak customer group', 'Add slice metrics', 'Aggregate success can conceal concentrated failure.']], traps: [['Tracking only model benchmarks', 'Use application outcomes on representative cases.'], ['Using a metric with no owner or threshold', 'It cannot trigger a release or response decision.']], sources: [['Define success criteria', EVALS]] },
  '4.2': { scenarios: [['The output has one correct value', 'Deterministic grader', 'Code is cheap and reliable.'], ['Quality is nuanced but scalable', 'Calibrated model rubric', 'A model grader can apply explicit criteria broadly.'], ['The decision is subjective or high stakes', 'Human review', 'Domain judgment anchors the evaluation.']], traps: [['Using only happy-path examples', 'Include edge, failure, adversarial, and refusal cases.'], ['Trusting an LLM judge without calibration', 'Compare it with expert ratings and monitor disagreement.']], sources: [['Define success criteria', EVALS]] },
  '4.3': { scenarios: [['Two prompts serve live traffic', 'Randomized A/B test', 'Concurrent assignment controls time effects.'], ['Live exposure is risky', 'Offline replay first', 'A fixed dataset provides safer evidence.'], ['A variant raises quality but doubles latency', 'Apply guardrail metrics', 'The primary metric alone is not a ship decision.']], traps: [['Changing prompt, model, and retrieval together', 'You cannot attribute the result.'], ['Stopping when the first metric looks positive', 'Predefine sample, duration, and decision rule.']], sources: [['Define success criteria', EVALS]] },
  '4.4': { scenarios: [['Errors begin after re-indexing', 'Inspect retrieval', 'The timing points to the changed layer.'], ['Claude selects the right tool with wrong arguments', 'Inspect schema and examples', 'Intent worked; contract filling failed.'], ['The same input fails intermittently', 'Inspect dependencies, sampling, and traces', 'Reproduction needs the entire execution path.']], traps: [['Swapping to a bigger model first', 'Localize the failure before paying for a global change.'], ['Editing several layers at once', 'Change one variable and create a regression case.']], sources: [['Handle tool calls', 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/handle-tool-calls'], ['Define success criteria', EVALS]] },
  '4.5': { scenarios: [['The same long policy repeats', 'Cache the stable prefix', 'This can reduce cost and time without removing information.'], ['Independent tool calls run serially', 'Parallelize them', 'Wall-clock time falls without changing the answer.'], ['Easy requests consume the strongest model', 'Route by difficulty', 'Reserve intelligence for cases that need it.']], traps: [['Optimizing price per token', 'Optimize cost per successful task.'], ['Trimming before measuring retrieval quality', 'Token savings can silently remove required evidence.']], sources: [['Cost and intelligence', COST], ['Prompt caching', CACHE]] },
  '4.6': { scenarios: [['Spend rises with no traffic growth', 'Break down tokens, cache, model, and retries', 'Cost telemetry localizes the change.'], ['Users report worse answers but uptime is green', 'Add outcome and quality monitoring', 'Infrastructure health is not behavior health.'], ['A safety event occurs', 'Trace, contain, and add a regression', 'Monitoring must connect to response and prevention.']], traps: [['Collecting signals with no alert rule', 'Define threshold, owner, runbook, and escalation.'], ['Storing all content indefinitely', 'Apply privacy, minimization, retention, and access controls.']], sources: [['Usage and Cost API', USAGE], ['Define success criteria', EVALS]] },

  '5.1': { scenarios: [['Retrieved text may contain instructions', 'Isolate it as untrusted data', 'External content must not outrank system policy.'], ['A tool can create irreversible impact', 'Require approval and validate arguments', 'A prompt alone cannot contain the consequence.'], ['Output must match a contract', 'Use strict schema and application validation', 'Hard checks catch malformed generations.']], traps: [['One giant safety prompt', 'Use independent controls at input, tool, output, and action boundaries.'], ['Logging after a dangerous action', 'Detection does not prevent the harm.']], sources: [['Sandboxing', CODE_SANDBOX], ['Tool use', TOOLS]] },
  '5.2': { scenarios: [['Answers invent unsupported facts', 'Hallucination control', 'Ground, cite, verify, and abstain.'], ['Untrusted content redirects the agent', 'Prompt-injection control', 'Isolate content and restrict capabilities.'], ['A dependency times out mid-action', 'Operational failure control', 'Retry, idempotency, fallback, and recovery matter.']], traps: [['Listing “hallucination” as the only risk', 'Assess data, integrations, security, people, and operations too.'], ['Naming a control without residual risk', 'State what can still fail and who accepts it.']], sources: [['Sandboxing', CODE_SANDBOX], ['Responsible scaling policy', 'https://www.anthropic.com/responsible-scaling-policy']] },
  '5.3': { scenarios: [['A draft email is easy to undo', 'User confirmation', 'Reversibility lowers the oversight burden.'], ['A medical or legal recommendation affects a person', 'Qualified reviewer', 'Expert judgment and accountability are required.'], ['Millions of low-impact outputs flow daily', 'Sampling and escalation', 'Full review would be infeasible; risk-based oversight scales.']], traps: [['Adding a human to every step', 'Review where uncertainty and consequence intersect.'], ['Showing the reviewer only the final answer', 'Provide evidence, provenance, and the available actions.']], sources: [['Define success criteria', EVALS]] },
  '5.4': { scenarios: [['Personal data crosses a region', 'Map transfer and processing basis', 'Jurisdiction and vendor flow alter obligations.'], ['Sensitive data enters prompts or logs', 'Minimize, control, and retain deliberately', 'The full data lifecycle is in scope.'], ['A regulated release needs approval', 'Produce control evidence', 'A policy claim is not auditable proof.']], traps: [['Treating a compliant model vendor as a compliant application', 'Your data flow, access, purpose, and operations still matter.'], ['Encoding legal conclusions without counsel', 'Architecture implements obligations; qualified owners interpret them.']] },
  '5.5': { scenarios: [['Overall accuracy is high but one group fares worse', 'Evaluate outcome slices', 'Averages can hide concentrated harm.'], ['Users cannot tell AI influenced a decision', 'Add disclosure and explanation', 'Transparency supports informed use and challenge.'], ['A person cannot correct an error', 'Add recourse and ownership', 'Accountability requires a remedy path.']], traps: [['Using demographic parity as the only definition of fairness', 'Choose fairness criteria for the decision context.'], ['Publishing a generic model card as full transparency', 'Explain the actual system, data use, limits, and recourse.']] },

  '6.1': { scenarios: [['Requirements say “fast and accurate”', 'Quantify both', 'Adjectives hide incompatible expectations.'], ['Stakeholders disagree on the current workflow', 'Map it together', 'Architecture should not automate an imagined process.'], ['Critical data access is uncertain', 'Test the assumption early', 'A missing dependency can invalidate the design.']], traps: [['Interviewing only the sponsor', 'Include users, operators, approvers, and affected groups.'], ['Jumping from discovery to solution', 'Record baseline, constraints, unknowns, and acceptance first.']] },
  '6.2': { scenarios: [['Executives compare two investments', 'Lead with value, exposure, and timing', 'Implementation detail does not answer their choice.'], ['Security reviews a new integration', 'Show identity, data, controls, and residual risk', 'They need boundary evidence.'], ['Engineering inherits the build', 'Show interfaces and failure behavior', 'They must implement and operate it.']], traps: [['Presenting one option', 'A decision needs credible alternatives and shared criteria.'], ['Hiding disadvantages of the recommendation', 'State consequences and revisit triggers.']] },
  '6.3': { scenarios: [['A demo generates new feature requests', 'Triage feedback', 'Separate bugs, requirements, risks, and preferences.'], ['Quality varies across runs', 'Use an eval-backed SLO', 'Examples alone cannot align expectations.'], ['Scope changes after approval', 'Use a named decision owner', 'Feedback must reach a controlled change process.']], traps: [['Calling every request urgent', 'Prioritize against outcomes, risk, and capacity.'], ['Promising deterministic perfection', 'Explain distributions, thresholds, fallbacks, and escalation.']] },
  '6.4': { scenarios: [['A developer asks what calls what', 'Component and sequence views', 'Runtime responsibility needs more than a context diagram.'], ['A reviewer asks why MCP was chosen', 'Architecture decision record', 'A diagram records shape, not rationale.'], ['Operations asks what to do during failure', 'Runbook', 'Recovery needs triggers, steps, owners, and rollback.']], traps: [['One giant diagram for every audience', 'Use connected views at different levels.'], ['Documentation that names components but no owners', 'Handoff includes responsibility and acceptance.']] },
  '6.5': { scenarios: [['A prototype meets a demo goal', 'Define production exit criteria', 'A demo does not prove operability or ownership.'], ['A production metric drifts', 'Feed the incident into evals and iteration', 'Lifecycle learning should change the system.'], ['The capability is no longer valuable', 'Retire deliberately', 'Remove access, data, cost, and operational burden.']], traps: [['Treating deployment as completion', 'Production requires SLOs, support, feedback, and ownership.'], ['Iterating without versioned evidence', 'Track which architecture and prompt produced each result.']] },

  '7.1': { scenarios: [['A rule must apply to every employee', 'Managed settings', 'Local project configuration must not override policy.'], ['A repository has build and style conventions', 'Project instructions', 'The guidance belongs with the code.'], ['A command or path is dangerous', 'Permission deny plus sandbox', 'Enforce access, not merely behavior.']], traps: [['Putting all rules in CLAUDE.md', 'It guides Claude but does not enforce OS or policy boundaries.'], ['Using personal settings for team policy', 'Choose a shared, versioned, or managed scope.']], sources: [['Claude Code configuration', CODE_CONFIG], ['Permissions', CODE_PERMISSIONS], ['Sandboxing', CODE_SANDBOX]] },
  '7.2': { scenarios: [['A change has clear acceptance tests', 'Delegate a bounded implementation loop', 'Claude can plan, edit, test, and report evidence.'], ['Several modules can change independently', 'Use isolated parallel work', 'Worktrees or separate ownership reduce collisions.'], ['A check should always run after edits', 'Automate with hooks or CI', 'Repeatable evidence should not depend on memory.']], traps: [['Granting broad permissions for speed', 'Automate safe actions and gate risky ones.'], ['Measuring productivity by generated lines', 'Measure accepted outcomes, cycle time, defects, and rework.']], sources: [['Claude Code parallel agents', CODE_AGENTS], ['Claude Code configuration', CODE_CONFIG]] },
  '7.3': { scenarios: [['The model output is wrong but tools are healthy', 'Inspect prompt, context, model, and eval trace', 'The behavior layer is implicated.'], ['A correct tool call fails', 'Inspect schema, auth, dependency, and environment', 'The failure occurs after model selection.'], ['Only production fails', 'Compare config, permissions, data, and network boundaries', 'Environment drift is more likely than source logic alone.']], traps: [['Retrying every failure', 'Retry only transient, idempotent operations with bounds.'], ['Closing after service recovers', 'Add a regression, detector, or runbook improvement.']], sources: [['Handle tool calls', 'https://platform.claude.com/docs/en/agents-and-tools/tool-use/handle-tool-calls'], ['Sandboxing', CODE_SANDBOX]] },
};
