export type ObjectiveVisual = {
  id: string;
  question: string;
  explain: string;
  flowTitle: string;
  flow: Array<[string, string]>;
  lensTitle: string;
  lenses: Array<[string, string]>;
  rule: string;
};

export const OBJECTIVE_VISUALS: Record<string, ObjectiveVisual> = Object.fromEntries(([
  ['1.1', 'Where does Claude actually help?', 'Translate the request into a job, a user, and a measurable outcome before choosing technology.', 'Turn the request into a solution shape', [['Business pain', 'What is slow, costly, risky, or impossible today?'], ['AI-suitable task', 'Language, ambiguity, or judgment is central'], ['Claude capability', 'Generate, classify, extract, reason, or act'], ['Success measure', 'Name the improvement and its threshold']], 'Separate the problem from the proposed feature', [['Feature request', '“Build a chatbot” names a surface. Ask what work should change.'], ['Business outcome', '“Cut policy-search time” becomes useful after adding a baseline and target.'], ['Acceptance criterion', '“Answers cite approved policy” is evidence the system can be tested against.']], 'A good Claude solution begins with a measurable job, not a request for an agent.'],
  ['1.2', 'How do all the parts form one production system?', 'Trace information from input to output, then close the loop with validation, monitoring, and feedback.', 'Follow the data through the architecture', [['Input', 'User, event, document, or system signal'], ['Processing', 'Prompt, retrieval, tools, and orchestration'], ['Output', 'Answer, artifact, or action'], ['Feedback', 'Validate, observe, learn, and improve']], 'Give every boundary an owner', [['Data boundary', 'Who may read it?'], ['Action boundary', 'Who may approve it?'], ['Failure boundary', 'What happens when it breaks?']], 'An end-to-end diagram is incomplete until it shows feedback and failure paths.'],
  ['1.3', 'Is this a call, a workflow, an agent, or an augmented LLM?', 'Choose the least complex pattern that can handle the uncertainty in the task.', 'Match uncertainty to autonomy', [['Single call', 'One bounded transformation'], ['Workflow', 'The steps are known in advance'], ['Agent', 'The path must be discovered at runtime'], ['Augmented LLM', 'Claude needs retrieval, tools, or memory']], 'Look for the clue in the scenario', [['Repeatable sequence', 'Workflow'], ['Open-ended route', 'Agent'], ['External knowledge', 'Retrieval augmentation']], 'Do not pay the cost of autonomy when a deterministic path already solves the problem.'],
  ['1.4', 'When should several agents collaborate?', 'Split work only when roles need different context, tools, permissions, or parallel execution.', 'Choose an orchestration shape', [['Router', 'Send each request to one specialist'], ['Parallel workers', 'Independent tasks run together'], ['Orchestrator-workers', 'A lead creates tasks dynamically'], ['Evaluator-optimizer', 'One produces; another critiques']], 'Multi-agent is a boundary decision', [['Shared context', 'Keep together'], ['Distinct privileges', 'Separate agents'], ['Heavy coordination', 'Question the split']], 'More agents add handoffs, latency, cost, and new failure modes; earn that complexity.'],
  ['1.5', 'How should a complex problem be broken apart?', 'Decompose around dependencies and verifiable outputs, not arbitrary prompt size.', 'Map the dependency graph', [['Define outcome', 'What final evidence proves success?'], ['Find subtasks', 'What can be completed independently?'], ['Order dependencies', 'What must happen first?'], ['Recombine', 'Validate interfaces and final result']], 'The dependency determines the pattern', [['Independent', 'Parallelize'], ['Sequential', 'Pipeline'], ['Unknown until runtime', 'Orchestrate dynamically']], 'A useful subtask has a clear input, a checkable output, and minimal hidden context.'],
  ['1.6', 'Why is this architecture worth building?', 'Connect technical choices to the business value they create and the service level they must sustain.', 'Trace design to value', [['Capability', 'What can the system do?'], ['Operational change', 'What work changes?'], ['Value pillar', 'Efficiency, productivity, transformation, or cost'], ['SLA', 'Quality, latency, availability, and risk threshold']], 'Use the right value language', [['Fewer handling minutes', 'Efficiency'], ['More cases per expert', 'Productivity'], ['A previously impossible service', 'Transformation']], 'A technical improvement matters only when it moves a business measure without breaking the SLA.'],

  ['2.1', 'Which Claude model fits this workload?', 'Select with task evidence across quality, latency, cost, context, and platform constraints.', 'Run the model selection funnel', [['Hard constraints', 'Region, modality, context, and availability'], ['Quality eval', 'Can it meet the task threshold?'], ['Operational eval', 'Measure latency and cost per success'], ['Choose', 'Smallest model that reliably clears the bar']], 'Avoid one-dimensional selection', [['Cheapest token', 'May increase retries'], ['Largest model', 'May add needless latency'], ['Best benchmark', 'May not fit your task']], 'Model selection is a workload decision, not a leaderboard decision.'],
  ['2.2', 'What belongs in the system prompt?', 'Write a stable behavioral contract, while enforcing hard boundaries outside the prompt.', 'Layer the instruction contract', [['Role and goal', 'What job is Claude doing?'], ['Rules and priorities', 'What must it do or avoid?'], ['Context and examples', 'What does good look like here?'], ['Output contract', 'What shape must the response take?']], 'Put controls in the layer that can hold', [['Tone and method', 'Prompt'], ['Valid structure', 'Schema validation'], ['Permission to act', 'Tool and policy layer']], 'Prompts guide behavior; permissions and validators enforce boundaries.'],
  ['2.3', 'Which prompting technique fits the task?', 'Add structure only when the simpler prompt fails on a measured example.', 'Escalate prompt structure deliberately', [['Zero-shot', 'Clear instruction with no examples'], ['Few-shot', '3–5 relevant, diverse examples'], ['Chain-of-thought / thinking', 'More reasoning for complex tasks'], ['Decomposition', 'Break work into checkable steps'], ['Tool use', 'Get facts or perform actions externally']], 'Examples should teach the boundary', [['Typical example', 'Shows the center'], ['Edge example', 'Shows where rules change'], ['Counterexample', 'Shows what not to do']], 'Use the lightest technique that passes the eval; extra prompting consumes context and can add confusion.'],
  ['2.4', 'What deserves space in the context window?', 'Treat context as a scarce working set: relevant, ordered, attributable, and small enough for the task.', 'Build the context budget', [['Reserve output', 'Leave room for the required answer'], ['Keep instructions', 'Stable rules and output contract'], ['Retrieve evidence', 'Only relevant chunks'], ['Trim history', 'Summarize or discard stale turns']], 'When context grows, choose intentionally', [['Needed repeatedly', 'Cache it'], ['Needed conditionally', 'Retrieve it'], ['No longer useful', 'Remove it']], 'A larger context window is capacity, not permission to send everything.'],
  ['2.5', 'What can be reused instead of rebuilt?', 'Separate stable instructions and capabilities from request-specific content.', 'Order content for reuse', [['Stable tools', 'Definitions change rarely'], ['System contract', 'Shared policy and behavior'], ['Reusable module or Skill', 'A named capability and its resources'], ['Dynamic turn', 'The current request goes last']], 'Choose the reuse mechanism', [['Repeated prefix', 'Prompt caching'], ['Shared instruction block', 'Modular prompt'], ['Reusable workflow + resources', 'Skill']], 'Stable first, variable last: that shape improves reuse, consistency, latency, and cost.'],

  ['3.1', 'Which capabilities should the agent not have?', 'Reduce the surface before adding controls; every unused tool is cost, confusion, and attack surface.', 'Shrink the capability surface', [['Observe real tasks', 'What actions are actually used?'], ['Remove', 'Delete capabilities the role never needs'], ['Consolidate', 'Merge actions that travel together'], ['Defer', 'Discover rare tools only when needed']], 'Removal beats compensation', [['Unused destructive tool', 'Delete it'], ['Necessary risky tool', 'Require approval'], ['Necessary read tool', 'Scope its data']], 'If the role never needs a capability, the safest guardrail is absence.'],
  ['3.2', 'Who is Claude acting as, and what may it do?', 'Keep authentication, authorization, and delegation distinct across every hop.', 'Trace identity through the call chain', [['Authenticate user', 'Who initiated the request?'], ['Authorize action', 'May this user do this operation?'], ['Delegate narrowly', 'Pass scoped, short-lived authority'], ['Audit actor', 'Record user, agent, tool, and result']], 'Watch for confused-deputy gaps', [['Shared service credential', 'Can erase user boundaries'], ['Broad token forwarding', 'Leaks excess privilege'], ['Per-action scope', 'Preserves least privilege']], 'A valid login does not authorize every tool action. Check permission at the resource boundary.'],
  ['3.3', 'How much speed is worth how much accuracy?', 'Measure the whole configuration on representative requests, then choose a point that clears both quality and latency thresholds.', 'Build the trade-off curve', [['Candidate configs', 'Model, retrieval depth, reranking, and tool count'], ['Measure quality', 'Task success on the eval set'], ['Measure latency', 'End-to-end percentiles'], ['Choose frontier', 'No other option is both faster and better']], 'Use the scenario constraint', [['Interactive UI', 'Tight latency budget'], ['High-stakes batch', 'Favor accuracy'], ['Easy then hard mix', 'Route by difficulty']], 'The best configuration is the one on the feasible frontier, not the fastest or most accurate in isolation.'],
  ['3.4', 'What must be observable when thousands of calls fail differently?', 'Capture a trace that connects the user request to model, retrieval, tool, policy, cost, and final outcome.', 'Follow one request across the system', [['Correlation ID', 'Join events across services'], ['Structured spans', 'Prompt, retrieval, model, and tools'], ['Metrics', 'Aggregate rate, latency, error, and cost'], ['Outcome signal', 'Did the user’s task succeed?']], 'Pick signal by question', [['What happened once?', 'Trace'], ['Is it widespread?', 'Metric'], ['Why did code fail?', 'Log']], 'Token and HTTP metrics are not enough; connect infrastructure behavior to task outcomes.'],
  ['3.5', 'How should documents become retrievable evidence?', 'Chunk and index around how users ask questions and how answers must be cited.', 'Design the RAG pipeline', [['Ingest', 'Parse, clean, and preserve metadata'], ['Chunk', 'Respect semantic boundaries and answer granularity'], ['Index', 'Embeddings plus lexical fields'], ['Retrieve and rerank', 'Find then order evidence'], ['Answer with citations', 'Ground and verify']], 'Chunking changes the failure mode', [['Too small', 'Loses surrounding meaning'], ['Too large', 'Dilutes relevance and wastes tokens'], ['Overlap', 'Preserves boundary context at a cost']], 'Choose chunking from the question-and-answer unit, not from an arbitrary token number.'],
  ['3.6', 'Which retrieval method matches this query?', 'Use the shape of the query and corpus to choose lexical, vector, structured, or hybrid retrieval.', 'Route by query shape', [['Exact identifier', 'Lexical or structured lookup'], ['Semantic question', 'Vector retrieval'], ['Mixed language and IDs', 'Hybrid retrieval'], ['Complex evidence need', 'Retrieve, filter, and rerank']], 'Metadata is part of retrieval', [['Tenant', 'Security filter'], ['Date or version', 'Freshness filter'], ['Document type', 'Precision filter']], 'Embedding similarity is one signal; exact terms, metadata, and reranking often decide the right evidence.'],
  ['3.7', 'Should this connection use an API, CLI, MCP, or A2A?', 'Choose the narrowest protocol that fits who is calling, what is shared, and how independently the systems operate.', 'Match the boundary to the mechanism', [['Direct service operation', 'API'], ['Local developer or system command', 'CLI'], ['Reusable tools/resources for models', 'MCP'], ['Independent agents coordinating', 'Agent-to-agent']], 'Protocol does not replace security', [['Discovery', 'What capabilities exist?'], ['Identity', 'Who is calling?'], ['Authorization', 'What may they do?']], 'Use MCP for a model-facing capability surface, not merely because a service has an API.'],
  ['3.8', 'Should Claude receive everything now or discover it later?', 'Balance immediate simplicity against context cost, selection confusion, and the need for late-bound capabilities.', 'Choose how capability enters context', [['Small stable set', 'Load it directly'], ['Large catalog', 'Expose a directory first'], ['Rare specialist', 'Discover on demand'], ['Chosen capability', 'Load only its useful detail']], 'Progressive discovery has a price', [['Benefit', 'Smaller, clearer context'], ['Cost', 'Extra lookup step and latency'], ['Risk', 'Discovery can miss the right tool']], 'Load the common core; discover the long tail when the catalog is large or changes often.'],

  ['4.1', 'What number means the system is good enough?', 'Turn each desired property into a metric, a dataset, and a threshold tied to the use case.', 'Write the scorecard before the test', [['Outcome', 'What should users achieve?'], ['Metric', 'How will it be counted?'], ['Threshold', 'What is acceptable?'], ['Slice', 'For whom or which cases must it hold?']], 'Balance the scorecard', [['Quality', 'Accuracy or task success'], ['Operations', 'Latency and cost'], ['Trust', 'Safety and security']], 'A metric without a threshold cannot tell you whether to ship.'],
  ['4.2', 'Which examples and graders make an eval trustworthy?', 'Represent production, isolate important slices, and use the cheapest grader that can judge each output reliably.', 'Build a mixed-method test system', [['Dataset', 'Normal, edge, failure, and adversarial cases'], ['Deterministic checks', 'Schemas, exact values, and invariants'], ['Model graders', 'Scaled rubric-based judgment'], ['Human review', 'Calibrate ambiguity and high-stakes quality']], 'Prevent a flattering dataset', [['Only happy paths', 'Inflated score'], ['Leaked examples', 'Overfitting'], ['Missing slices', 'Hidden failures']], 'The eval set should resemble the traffic you fear, not just the demo you like.'],
  ['4.3', 'Did the change actually improve the system?', 'Compare variants on the same population, with a primary metric and guardrails chosen before looking at results.', 'Run a controlled improvement loop', [['Hypothesis', 'Name the expected change'], ['Randomize or replay', 'Keep comparison fair'], ['Measure', 'Primary metric plus guardrails'], ['Decide', 'Ship, revise, or stop'], ['Regress', 'Keep the winning cases']], 'Read the result in context', [['Better quality, huge cost', 'Trade-off, not a win'], ['Small sample', 'Uncertain result'], ['Slice regresses', 'Investigate harm']], 'Do not move the goalposts after seeing the scores.'],
  ['4.4', 'Which layer is responsible for the failure?', 'Use the symptom and the most recent change to test the cheapest plausible cause first.', 'Localize before changing', [['Reproduce', 'Capture the failing input and trace'], ['Classify symptom', 'Wrong fact, format, action, or refusal'], ['Inspect layers', 'Data, retrieval, prompt, model, tool, orchestration'], ['Change one thing', 'Confirm cause with a regression test']], 'Symptoms point to layers', [['Wrong after document refresh', 'Retrieval or index'], ['Correct data, wrong format', 'Prompt or validation'], ['Tool call denied', 'Auth or permissions']], 'A confident wrong answer is a symptom, not proof that the model is the cause.'],
  ['4.5', 'Where can cost or latency fall without losing the outcome?', 'Optimize after measuring the end-to-end path and protect task quality with regression evals.', 'Work down the cost-and-latency stack', [['Remove waste', 'Trim irrelevant context and unused tools'], ['Reuse', 'Cache stable prefixes and retrieval'], ['Route', 'Use smaller models for easier work'], ['Parallelize', 'Run independent calls together'], ['Re-evaluate', 'Check quality and safety']], 'Optimize the bottleneck', [['High input tokens', 'Context and caching'], ['Long serial path', 'Parallelism or fewer steps'], ['Repeated failures', 'Quality fix before downsizing']], 'Cost per successful task matters more than cost per token.'],
  ['4.6', 'How will production tell us it is drifting?', 'Combine system telemetry with model behavior and user outcomes, then attach thresholds and owners.', 'Turn events into operations', [['Instrument', 'Trace prompts, retrieval, tools, and responses'], ['Aggregate', 'Quality, latency, cost, error, and safety'], ['Alert', 'Thresholds, anomalies, and SLO burn'], ['Respond', 'Owner, runbook, and rollback'], ['Learn', 'Add failures to evals']], 'Watch three levels', [['Infrastructure', 'Is it available?'], ['Behavior', 'Is it correct and safe?'], ['Outcome', 'Did the user succeed?']], 'Observability becomes operational only when a signal has a threshold, an owner, and a response.'],

  ['5.1', 'Which safety layer stops this failure?', 'Use multiple independent controls before, during, and after generation or tool use.', 'Build defense in depth', [['Input controls', 'Classify, sanitize, and bound'], ['Model constraints', 'Clear behavior and least privilege'], ['Output validation', 'Schema, policy, and evidence checks'], ['Action gate', 'Confirmation or human approval'], ['Audit', 'Record and review']], 'Hard controls beat hopeful wording', [['Formatting', 'Schema'], ['Data access', 'Authorization'], ['Irreversible action', 'Approval gate']], 'Safety is a system property; no single prompt is the boundary.'],
  ['5.2', 'How can this LLM system fail?', 'Identify failure modes across data, model behavior, integrations, people, and operations before assigning controls.', 'Run the risk chain', [['Asset', 'What could be harmed?'], ['Threat or limitation', 'How could failure begin?'], ['Failure mode', 'What specifically goes wrong?'], ['Impact', 'Who is affected and how badly?'], ['Control and residual risk', 'What remains after mitigation?']], 'Do not collapse unlike risks', [['Hallucination', 'Ground and verify'], ['Prompt injection', 'Isolate and restrict'], ['Outage', 'Fallback and recovery']], 'Name a concrete failure and impact; “AI is risky” cannot guide an architecture.'],
  ['5.3', 'Where should a human enter the loop?', 'Place review where uncertainty meets consequence, and give the reviewer enough evidence and authority to act.', 'Scale oversight with impact', [['Low impact', 'Monitor and sample'], ['Reversible action', 'User confirmation'], ['Material decision', 'Qualified review'], ['Regulated or irreversible', 'Mandatory approval and audit']], 'Design the review, not just the checkbox', [['Evidence', 'Show sources and rationale'], ['Action', 'Approve, edit, reject, or escalate'], ['SLA', 'Define what happens while waiting']], 'Human review works only when the person can understand, change, and own the decision.'],
  ['5.4', 'How does regulation change the architecture?', 'Translate legal obligations into data flows, controls, evidence, and operating responsibilities with qualified counsel.', 'Turn an obligation into a control', [['Scope', 'Which data, users, and jurisdictions apply?'], ['Data map', 'Where is information collected, sent, and stored?'], ['Control', 'Minimize, authorize, retain, delete, and audit'], ['Evidence', 'Prove the control operated'], ['Owner', 'Assign review and response']], 'Common architecture pressure', [['GDPR', 'Purpose, minimization, rights, transfer'], ['HIPAA', 'Protected data and safeguards'], ['FedRAMP', 'Authorized cloud controls and evidence']], 'Compliance is not a model setting; it is traceable control across the whole data lifecycle.'],
  ['5.5', 'Who benefits, who can be harmed, and who can challenge the output?', 'Evaluate bias, fairness, transparency, and accountability in the actual decision context.', 'Review the impact pathway', [['Affected groups', 'Who receives the outcome?'], ['Representation', 'Who is missing from data and tests?'], ['Outcome slices', 'Where do error rates differ?'], ['Explanation and recourse', 'Can people understand and contest?'], ['Accountability', 'Who owns correction?']], 'Different goals need different checks', [['Bias', 'Systematic skew'], ['Fairness', 'Comparable treatment or outcomes'], ['Transparency', 'Visible use, limits, and evidence']], 'Average accuracy can hide concentrated harm; inspect outcomes by meaningful group and use case.'],

  ['6.1', 'What must be learned before proposing an architecture?', 'Use structured discovery to uncover the job, users, workflow, constraints, risks, and measurable baseline.', 'Move from story to requirements', [['Stakeholders', 'Users, owners, approvers, and affected groups'], ['Current workflow', 'Steps, friction, exceptions, and baseline'], ['Constraints', 'Data, security, legal, budget, and timing'], ['Success', 'Metric, threshold, and acceptance owner'], ['Unknowns', 'Assumptions to test early']], 'Ask for evidence, not adjectives', [['“Too slow”', 'How long today?'], ['“Must be accurate”', 'What threshold and on which cases?'], ['“Secure”', 'Against which threats?']], 'Discovery is complete enough when assumptions and acceptance criteria are visible.'],
  ['6.2', 'How do you make an architecture choice understandable?', 'Show the options against agreed criteria, then record what was chosen, why, and what would change the choice.', 'Make the trade-off legible', [['Decision', 'What must be chosen now?'], ['Options', 'Include a credible alternative'], ['Criteria', 'Quality, latency, cost, risk, and operability'], ['Recommendation', 'Explain the winning trade-off'], ['Consequence', 'State debt, risk, and revisit trigger']], 'Match detail to the audience', [['Executive', 'Value, exposure, timing'], ['Security or legal', 'Data, controls, residual risk'], ['Engineering', 'Interfaces, failure modes, operations']], 'A recommendation without alternatives sounds like preference; criteria make it defensible.'],
  ['6.3', 'How do expectations stay aligned after kickoff?', 'Turn feedback into a visible loop with decision rights, service levels, and a controlled way to change scope.', 'Operate the alignment loop', [['Demo or evidence', 'Show real system behavior'], ['Feedback', 'Capture concern and desired outcome'], ['Triage', 'Bug, requirement, risk, or preference'], ['Decision', 'Owner accepts, rejects, or reprioritizes'], ['Update', 'Backlog, SLA, docs, and expectations']], 'Make non-determinism discussable', [['Quality SLO', 'Target over an eval slice'], ['Latency SLO', 'Percentile, not anecdote'], ['Escalation', 'Who acts when the bar is missed?']], 'Feedback is useful only when it reaches a named decision and changes a shared artifact.'],
  ['6.4', 'What documentation lets another team build and operate this?', 'Document boundaries, interfaces, decisions, risks, and runbooks at the level the next owner needs.', 'Create a connected document set', [['Context diagram', 'System, people, and external boundaries'], ['Component and sequence views', 'Responsibilities and runtime flow'], ['Decision records', 'Choice, alternatives, and consequences'], ['Implementation guidance', 'Contracts, patterns, and acceptance tests'], ['Runbook', 'Monitor, recover, escalate, and roll back']], 'Each artifact answers a different question', [['Diagram', 'What connects?'], ['ADR', 'Why this choice?'], ['Runbook', 'What do we do now?']], 'The handoff succeeds when the receiving team can make the next safe decision without the original architect.'],
  ['6.5', 'What changes as the system moves through its lifecycle?', 'Carry evidence, ownership, risk, and feedback from discovery through retirement.', 'Follow the lifecycle', [['Discover', 'Problem, baseline, constraints'], ['Design', 'Architecture, evals, and controls'], ['Handoff', 'Acceptance, owners, and runbooks'], ['Operate', 'SLOs, incidents, feedback'], ['Iterate or retire', 'Regression evidence and exit plan']], 'Every phase has an exit signal', [['Discovery', 'Accepted problem and measures'], ['Design', 'Reviewed trade-offs and test plan'], ['Production', 'SLOs, owners, rollback ready']], 'A system is not delivered at deployment; it is delivered when ownership and learning continue without the project team.'],

  ['7.1', 'Where should team-wide Claude configuration live?', 'Separate organization policy, repository guidance, permissions, hooks, and sandboxing by enforcement strength and scope.', 'Place configuration in the right layer', [['Managed settings', 'Organization-wide policy and approved integrations'], ['Project instructions', 'Repository context and conventions'], ['Permissions and hooks', 'Allow, ask, deny, and validate'], ['Sandbox', 'OS-level file and network boundary'], ['Personal settings', 'Preferences that do not weaken policy']], 'Guidance is not enforcement', [['CLAUDE.md', 'Tells Claude how to work'], ['Permission rule', 'Controls a capability'], ['Managed policy', 'Prevents local override']], 'Put a rule in the narrowest layer that can reliably enforce it for the intended scope.'],
  ['7.2', 'Where can AI shorten the development loop safely?', 'Use Claude for bounded work with explicit context, tests, review, and permission limits.', 'Build an assisted workflow', [['Issue', 'Clear goal and acceptance criteria'], ['Plan', 'Inspect code and propose changes'], ['Implement', 'Small, reviewable edits'], ['Verify', 'Tests, lint, build, and security checks'], ['Review', 'Human owns the merge and outcome']], 'Automate repeated evidence', [['Formatting', 'Hook or CI'], ['Regression', 'Test suite'], ['Risky command', 'Permission gate']], 'Speed comes from closing the feedback loop, not from skipping it.'],
  ['7.3', 'How should a team debug an AI-enabled system?', 'Preserve enough evidence to reproduce the failure, isolate its layer, recover service, and prevent recurrence.', 'Run the operational loop', [['Detect', 'Alert or user report'], ['Triage', 'Impact, scope, and recent change'], ['Trace', 'Context, model, retrieval, tools, and permissions'], ['Mitigate', 'Retry, fallback, rollback, or disable'], ['Prevent', 'Regression test, runbook, and durable fix']], 'Route by evidence', [['Model response wrong', 'Inspect prompt and context'], ['Tool failed', 'Inspect schema, auth, and dependency'], ['Only production fails', 'Inspect environment and policy']], 'The incident is not closed until the failure is reproducible or its recurrence is detectable.'],
] as Array<[string, string, string, string, Array<[string, string]>, string, Array<[string, string]>, string]>).map(([id, question, explain, flowTitle, flow, lensTitle, lenses, rule]) => [id, { id, question, explain, flowTitle, flow, lensTitle, lenses, rule }]));
