export type ObjectiveLesson = {
  idea: string;
  lensIntro: string;
  example: {
    situation: string;
    tempting: string;
    move: string;
    why: string;
  };
};

export const OBJECTIVE_LESSONS: Record<string, ObjectiveLesson> = {
  '1.1': { idea: 'Stakeholders usually arrive with a feature in mind. The architect’s first job is to move one level down: identify the work that should change, then make that change measurable. Only then can you tell whether Claude is suitable and what the system must prove.', lensIntro: 'These statements are not interchangeable. One names a surface, one names the result the business wants, and one names evidence that the result is trustworthy.', example: { situation: 'Support agents spend 12 minutes searching several policy sites before answering a customer.', tempting: '“Build a support chatbot.” That commits to an interface but says nothing about the problem, the quality bar, or whether an agent is needed.', move: 'Target a median search time under 3 minutes. Retrieve only current approved policy, cite it in every answer, and abstain when evidence is missing.', why: 'Now model choice, retrieval, interface, and evaluation can all be judged against the same outcome.' } },
  '1.2': { idea: 'An LLM call is only one component. A production architecture must show how data enters, how it is transformed, where external actions happen, how outputs are checked, and how real outcomes return as feedback.', lensIntro: 'Use boundaries to expose responsibilities the happy-path arrow hides.', example: { situation: 'A claims assistant reads a form, checks policy, drafts a recommendation, and updates the case.', tempting: 'Draw “form → Claude → decision” and call it the architecture.', move: 'Separate ingestion, validation, retrieval, generation, human approval, case update, audit, and outcome monitoring.', why: 'Each component now has an owner, failure behavior, permission boundary, and testable contract.' } },
  '1.3': { idea: 'Pattern selection is about who controls the path. Code controls a workflow; Claude controls some next-step choices in an agent; an augmented LLM is simply a model call supplied with retrieval, tools, or memory.', lensIntro: 'Look for the uncertainty in the route, not for fashionable words in the prompt.', example: { situation: 'Every invoice follows extraction, validation, ERP lookup, and approval.', tempting: 'Use an autonomous agent because several steps are involved.', move: 'Use a workflow. Let Claude extract ambiguous fields, while code owns the fixed sequence and approval branch.', why: 'The design keeps flexibility only where ambiguity exists and makes the rest predictable.' } },
  '1.4': { idea: 'Multiple agents are useful when separation creates a real advantage: independent context, specialist tools, distinct permissions, parallel work, or productive critique. They also create a distributed system with coordination, state, budget, and failure concerns.', lensIntro: 'Agent count is not the decision. The decision is where context, authority, state, and coordination should live.', example: { situation: 'A research task must inspect legal, technical, and commercial evidence, then reconcile conflicts.', tempting: 'Give three agents the same broad prompt and ask the lead to merge their prose.', move: 'Give each worker a bounded question, evidence sources, tool allowlist, return schema, trace ID, and budget. Make the coordinator own dependencies and the synthesizer resolve conflicts.', why: 'Parallelism now produces complementary evidence instead of duplicated work and an uncheckable summary.' } },
  '1.5': { idea: 'Good decomposition reduces hidden dependencies. Each subtask should have a bounded input, a checkable output, and a clear relationship to the final result.', lensIntro: 'The dependency graph tells you whether to chain, parallelize, or plan dynamically.', example: { situation: 'A migration assessment needs inventory, compatibility analysis, cost estimates, and a rollout plan.', tempting: 'Split the source material into four equally sized chunks.', move: 'Inventory first; run compatibility and cost analysis from that shared artifact; create the rollout only after both return.', why: 'The split follows information dependencies, so workers do not invent incompatible assumptions.' } },
  '1.6': { idea: 'Value pillars translate architecture into an outcome a sponsor can own. Every technical measure should connect to changed work or a service level: faster, cheaper, more productive, newly possible, or more reliable.', lensIntro: 'Classify the value before choosing the metric; different value claims require different evidence.', example: { situation: 'A summarization system cuts output cost by 40 percent but requires more human rework.', tempting: 'Declare success because token spend fell.', move: 'Measure cost per accepted summary, review minutes, throughput, and the quality SLA together.', why: 'The scorecard reveals whether technical savings created business value or merely moved cost to people.' } },

  '2.1': { idea: 'A model is part of a configuration, not a prize. Choose the least expensive configuration that reliably clears task quality and operational constraints on your own evaluation set.', lensIntro: 'Capability, speed, and price trade against each other; “best” only has meaning after constraints are named.', example: { situation: 'Most tickets are simple classifications, but a small group needs nuanced policy reasoning.', tempting: 'Run every ticket through the strongest model.', move: 'Evaluate a fast model on all cases, route uncertain or high-risk cases to a stronger model, and measure cost per correct resolution.', why: 'The architecture buys intelligence only where it changes the outcome.' } },
  '2.2': { idea: 'The system prompt is a behavioral contract: role, priorities, process, context rules, and output shape. It can guide Claude, but it cannot enforce identity, permission, or irreversible-action boundaries.', lensIntro: 'Place each requirement in the layer capable of guaranteeing it.', example: { situation: 'A finance assistant may draft payments but only managers may submit them.', tempting: 'Add “never submit without approval” to the system prompt.', move: 'Prompt Claude to draft, validate the payment schema, and require backend authorization plus manager approval before the submit tool runs.', why: 'A model mistake can affect the draft, but it cannot bypass the transaction boundary.' } },
  '2.3': { idea: 'Prompting techniques add different kinds of information. Zero-shot adds instruction, few-shot adds demonstrations, and thinking or decomposition adds reasoning structure. Choose by observed failure, not habit.', lensIntro: 'Examples teach a boundary only when they are relevant, varied, and explicit about what changes.', example: { situation: 'A classifier handles ordinary requests but confuses cancellations with temporary pauses.', tempting: 'Add a longer role description and ask it to think harder.', move: 'Add a few diverse pause/cancel examples, including an edge case, then re-run the confusion slice.', why: 'The prompt now supplies the missing distinction, and the eval proves whether it was learned.' } },
  '2.4': { idea: 'The context window is Claude’s working set, not a document warehouse. Instructions, history, tools, retrieved text, tool results, thinking, and the new output all compete for the same capacity.', lensIntro: 'Decide whether information should remain, be summarized, be retrieved later, or be removed.', example: { situation: 'A long-running support agent repeats policies and accumulates full API payloads.', tempting: 'Move to a model with a larger context window.', move: 'Cache stable policy, retrieve case-specific sections, return only useful tool fields, and compact stale conversation history.', why: 'Claude sees a smaller, more relevant working set and the system delays context exhaustion.' } },
  '2.5': { idea: 'Reuse works when stable content is separated from variable content. Prompt caching reuses an identical prefix; templates reuse structure; Skills package reusable instructions, workflow, and resources.', lensIntro: 'Choose the reuse mechanism according to what stays stable and how broadly it should travel.', example: { situation: 'Every analysis request sends the same tool definitions, policy, examples, and a different report.', tempting: 'Mark the changing report as cacheable.', move: 'Order tools, system policy, and examples first; place the cache breakpoint after that stable prefix; send the report and question last.', why: 'Subsequent requests can hit the same prefix without pretending variable content is reusable.' } },

  '3.1': { idea: 'Capability bloat has two costs: it gives the model more ways to make a harmful choice and consumes context that makes tool selection harder. The first control is subtraction.', lensIntro: 'Removal, consolidation, and discovery solve different kinds of bloat.', example: { situation: 'A support agent can read cases, draft replies, issue refunds, and delete accounts, but staff only read and draft.', tempting: 'Keep every tool and log risky actions.', move: 'Remove refund and deletion from the role’s toolset entirely.', why: 'The unnecessary attack surface disappears instead of being monitored after a mistake.' } },
  '3.2': { idea: 'Authentication answers who is calling. Authorization answers what that identity may do to this resource. Delegation answers how narrowly the agent may act for that person across another boundary.', lensIntro: 'Trace identity and permission separately through every hop.', example: { situation: 'A shared backend token lets an assistant read any customer record.', tempting: 'Trust the application because the user logged in upstream.', move: 'Carry user identity, enforce tenant and record permission at the data service, and issue a narrow short-lived delegated credential.', why: 'The agent cannot become a confused deputy that turns one valid login into universal access.' } },
  '3.3': { idea: 'Accuracy and latency form a curve, not two independent scores. Retrieval depth, reranking, model capability, tool calls, and retries can improve quality while increasing elapsed time.', lensIntro: 'The use case determines which part of the trade-off curve is feasible.', example: { situation: 'Search must respond in two seconds, while compliance review can run overnight.', tempting: 'Use one “best” configuration for both.', move: 'Set separate quality and percentile-latency thresholds; use shallow retrieval for search and deeper verified processing for review.', why: 'Each workload receives the accuracy it needs inside the time it can afford.' } },
  '3.4': { idea: 'Observability must reconstruct one request and summarize many requests. Traces explain a path, logs explain events, metrics reveal population behavior, and outcome signals say whether users succeeded.', lensIntro: 'Choose the signal that answers the operational question, then connect all signals with identity and correlation IDs.', example: { situation: 'Latency rises, but model response time is unchanged.', tempting: 'Inspect token counts only.', move: 'Trace retrieval, queues, tool calls, retries, and generation; compare stage percentiles across affected traffic.', why: 'The slow boundary becomes visible instead of being blamed on the model by default.' } },
  '3.5': { idea: 'RAG quality begins before generation. Parsing, metadata, chunk boundaries, indexes, filters, retrieval, and reranking determine which evidence Claude can see.', lensIntro: 'Chunk size changes both recall and precision; choose it from the answer unit and document structure.', example: { situation: 'Policy answers require a rule plus exceptions located in the same section.', tempting: 'Split every document into fixed 200-token chunks.', move: 'Chunk on headings and semantic sections, preserve policy version metadata, add modest overlap, and test retrieval recall on exception questions.', why: 'Each retrieved unit carries enough meaning to answer and enough metadata to verify freshness.' } },
  '3.6': { idea: 'Retrieval methods exploit different signals. Lexical search preserves exact words, vectors capture meaning, structured queries enforce fields, and rerankers improve ordering after broad recall.', lensIntro: 'Match the strongest signal in the query to the shape of the corpus.', example: { situation: 'Users search for exact product codes and also describe symptoms in plain language.', tempting: 'Use vector similarity for every query.', move: 'Combine lexical and vector retrieval, filter by tenant and active version, then rerank the merged candidates.', why: 'Exact identifiers survive while semantic descriptions still find related content.' } },
  '3.7': { idea: 'Integration mechanisms describe different relationships. An API calls a service, a CLI operates a local program, MCP exposes model-facing tools and resources, and A2A coordinates independent agents.', lensIntro: 'Select from the caller, boundary, reuse, discovery, and autonomy, not from protocol popularity.', example: { situation: 'Several Claude applications need the same governed access to an internal catalog.', tempting: 'Give each application bespoke API instructions in its prompt.', move: 'Expose a narrow MCP surface backed by the catalog API, with shared schemas and per-user authorization.', why: 'Applications reuse one model-facing contract while the existing service remains the system of record.' } },
  '3.8': { idea: 'Progressive discovery keeps a large capability catalog out of the working context until it is relevant. It saves attention and tokens but adds a discovery step that can be slow or wrong.', lensIntro: 'First identify what causes context pressure: definitions, results, history, or retrieved data.', example: { situation: 'An enterprise catalog exposes 300 tools, while most requests use fewer than five.', tempting: 'Load all schemas and rely on Claude to ignore the rest.', move: 'Load the common core, search compact tool metadata, then inject only selected definitions.', why: 'Claude chooses from a relevant shortlist without paying the full context cost every turn.' } },

  '4.1': { idea: 'An evaluation metric becomes useful only when it names the behavior, how it is measured, the population or slice, and the threshold that changes a decision.', lensIntro: 'Quality, operations, and trust form one release scorecard.', example: { situation: 'A team says its assistant must be accurate and fast.', tempting: 'Track generic helpfulness and average response time.', move: 'Require at least 90 percent expert pass overall, zero must-refuse failures, and p95 latency under three seconds on representative traffic.', why: 'The team can now decide whether to release and see which constraint failed.' } },
  '4.2': { idea: 'A trustworthy eval combines representative cases with graders suited to each output. Code checks facts and invariants, model graders scale rubrics, and humans calibrate ambiguity and high-impact judgment.', lensIntro: 'Dataset design and grader design are inseparable: the case determines what reliable judgment looks like.', example: { situation: 'A support assistant must return the right policy, cite it, use an appropriate tone, and refuse unsafe requests.', tempting: 'Use one LLM judge and one average score.', move: 'Use deterministic citation checks, an expert-calibrated tone rubric, separate refusal cases, and slice-level reporting.', why: 'Each property is judged by an appropriate method and critical failures cannot hide in an average.' } },
  '4.3': { idea: 'A/B testing estimates the effect of one change by comparing variants on equivalent cases or traffic. Decide the hypothesis, primary metric, guardrails, and stopping rule before seeing results.', lensIntro: 'A higher primary score is not a win if an important guardrail regresses.', example: { situation: 'A new prompt may improve answer quality but adds more output tokens.', tempting: 'Ship after ten examples look better.', move: 'Replay a fixed eval first, then randomize live traffic; compare quality while guarding cost, latency, safety, and key slices.', why: 'The result is attributable, large enough to trust, and tied to a release rule.' } },
  '4.4': { idea: 'LLM-system symptoms rarely identify their own cause. Diagnose by reproducing the request, locating the first incorrect boundary, and testing the layer most connected to the recent change.', lensIntro: 'Use symptom timing and trace evidence to narrow the search before editing anything.', example: { situation: 'Answers become confidently wrong immediately after documents are refreshed.', tempting: 'Increase temperature or switch to a larger model.', move: 'Inspect parsing, embeddings, index version, retrieval results, metadata filters, and citations for the failing query.', why: 'The change and symptom both point to evidence entering the model, not to model capability.' } },
  '4.5': { idea: 'Optimization should remove waste before trading away intelligence. Measure the end-to-end bottleneck, preserve quality with regression evals, and optimize cost per successful task.', lensIntro: 'Different bottlenecks require different levers; model downsizing is only one of them.', example: { situation: 'An agent repeatedly sends a long policy and performs three independent lookups in sequence.', tempting: 'Move everything to the smallest model.', move: 'Cache the stable prefix, trim unused tool output, run lookups in parallel, then evaluate whether easy cases can use a smaller model.', why: 'Free efficiency gains happen before any deliberate quality trade-off.' } },
  '4.6': { idea: 'Production monitoring connects system health, model behavior, and user outcomes. A useful signal has a threshold, an owner, a runbook, and a feedback path into evaluation.', lensIntro: 'Infrastructure can be green while users receive bad answers, so observe all three levels.', example: { situation: 'API errors remain flat, but customers increasingly reopen resolved tickets.', tempting: 'Conclude the system is healthy because uptime is high.', move: 'Monitor reopen rate and sampled answer quality beside latency, cost, retrieval, tool errors, and model versions.', why: 'The outcome signal reveals behavioral drift that infrastructure metrics cannot see.' } },

  '5.1': { idea: 'Guardrails are independent controls placed around untrusted input, model behavior, tool use, outputs, and consequential actions. Their job is to contain failure even when another layer is wrong.', lensIntro: 'Match control strength to consequence: guidance influences, validation rejects, authorization prevents, and approval transfers responsibility.', example: { situation: 'An email agent reads untrusted messages and can send replies.', tempting: 'Tell Claude to ignore malicious instructions and always be careful.', move: 'Treat email as quoted data, restrict available tools, validate recipients and content, and require confirmation before sending.', why: 'Prompt injection may affect a draft but cannot silently expand capability or execute the action.' } },
  '5.2': { idea: 'Risk analysis connects an asset to a concrete failure, its cause, consequence, control, and residual exposure. LLM risks span data, behavior, integrations, operations, and human use.', lensIntro: 'Different failure modes need different controls; “add a guardrail” is not a risk treatment.', example: { situation: 'A research assistant can hallucinate sources, reveal private documents, or fail during a long tool sequence.', tempting: 'List “AI may be inaccurate” as the risk.', move: 'Model each failure separately with grounding and citation checks, access controls, and bounded retries plus recovery.', why: 'Specific failure paths can be tested, owned, and accepted instead of merely acknowledged.' } },
  '5.3': { idea: 'Human-in-the-loop design is risk-based. The reviewer should enter where uncertainty meets consequence, see the evidence needed to judge, and have a clear action and response time.', lensIntro: 'Oversight ranges from sampling to mandatory approval; it is not always a person reading every output.', example: { situation: 'A system drafts routine replies and recommends account termination for serious violations.', tempting: 'Ask users to approve every draft equally.', move: 'Sample routine replies, require confirmation for reversible account changes, and route termination to a qualified reviewer with evidence.', why: 'Human attention concentrates where expertise and accountability materially reduce risk.' } },
  '5.4': { idea: 'Compliance requirements become architecture through data mapping, purpose and access rules, retention, regional flow, audit evidence, and named responsibility. Vendor compliance alone does not make the application compliant.', lensIntro: 'Start with which obligation applies, then trace it to a control and evidence across the data lifecycle.', example: { situation: 'A healthcare assistant sends patient content to a model and retains traces for debugging.', tempting: 'Approve it because the model provider advertises security certifications.', move: 'Confirm legal scope with counsel; map data flow, minimize fields, configure approved processing, restrict trace access and retention, and document evidence.', why: 'The architecture now implements the organization’s actual obligations rather than borrowing a vendor claim.' } },
  '5.5': { idea: 'Ethical analysis asks how errors and benefits are distributed, whether people understand the system’s role, and whether they can challenge or correct an outcome.', lensIntro: 'Bias, fairness, and transparency describe related but different questions and require use-case-specific evidence.', example: { situation: 'A hiring assistant has high overall accuracy but rejects qualified candidates from one language group more often.', tempting: 'Publish the aggregate score and a generic AI disclosure.', move: 'Evaluate error slices, inspect data representation and decision criteria, add human review and recourse, and name the owner of remediation.', why: 'The concentrated harm becomes visible and affected people have a path to correction.' } },

  '6.1': { idea: 'Structured discovery converts stories and adjectives into a shared model of users, workflow, baseline, constraints, risks, unknowns, and acceptance. It reduces the chance of solving the sponsor’s imagined problem.', lensIntro: 'Ask for observable evidence whenever a requirement uses words such as fast, accurate, secure, or easy.', example: { situation: 'A sponsor says analysts need faster answers from company data.', tempting: 'Estimate a RAG build immediately.', move: 'Observe the current workflow, measure search time and error cost, identify sources and permissions, define answer and refusal cases, and name the acceptance owner.', why: 'The team can test the riskiest assumptions before committing to an architecture.' } },
  '6.2': { idea: 'Architecture communication makes a choice inspectable. Present the decision, credible alternatives, shared criteria, recommendation, consequences, and the condition that would trigger reconsideration.', lensIntro: 'The same decision needs different evidence for executives, control owners, and implementers.', example: { situation: 'A team must choose between direct API integration and an MCP server.', tempting: 'Present only MCP and list its features.', move: 'Compare reuse, discovery, latency, ownership, security, and implementation cost; recommend one and record when the alternative becomes better.', why: 'Stakeholders can challenge the criteria instead of debating personal preference.' } },
  '6.3': { idea: 'Expectation alignment is an operating loop, not a kickoff meeting. Real system evidence produces feedback, a named owner classifies it, and shared artifacts record the resulting decision.', lensIntro: 'Use distributions and service levels to discuss non-deterministic behavior precisely.', example: { situation: 'A demo produces conflicting requests for higher quality, lower latency, and more features.', tempting: 'Add every request to one backlog.', move: 'Classify feedback as defect, risk, requirement, or preference; evaluate it against agreed SLOs and outcomes; have the owner reprioritize visibly.', why: 'Feedback changes a controlled plan without silently changing the release promise.' } },
  '6.4': { idea: 'Documentation is a set of connected views. Diagrams show structure and runtime flow, decision records explain why, implementation guidance defines contracts, and runbooks support operation.', lensIntro: 'Choose the artifact from the question the next owner needs answered.', example: { situation: 'A delivery team receives one architecture diagram with boxes for Claude, database, and API.', tempting: 'Add more boxes and arrows to the same diagram.', move: 'Provide context and sequence views, interface schemas, ADRs, threat and failure notes, acceptance tests, owner map, and an operational runbook.', why: 'Builders can implement the contracts and operators can recover the service without finding the original architect.' } },
  '6.5': { idea: 'Lifecycle management carries evidence and ownership from discovery through design, handoff, production learning, iteration, and retirement. Each phase needs an exit condition.', lensIntro: 'Deployment is a transition between owners, not the finish line.', example: { situation: 'A successful pilot is ready for a company-wide launch.', tempting: 'Deploy the pilot and monitor basic uptime.', move: 'Require production evals, control review, SLOs, named support and data owners, rollback, feedback intake, change triggers, and a retirement plan.', why: 'The system becomes operable and improvable rather than merely available.' } },

  '7.1': { idea: 'Team configuration has layers with different scope and enforcement. Managed settings express organization policy; project files share repository guidance; permissions and hooks control actions; the sandbox creates an OS boundary.', lensIntro: 'A rule belongs in the narrowest layer that can reliably enforce it for everyone in scope.', example: { situation: 'A company wants consistent coding guidance and must prevent access to secrets across every repository.', tempting: 'Put both requirements in each repository’s CLAUDE.md.', move: 'Keep coding conventions in versioned project instructions; deploy non-overridable managed deny rules and sandbox restrictions for secret paths and network access.', why: 'Guidance stays close to the code while security does not depend on the model following prose.' } },
  '7.2': { idea: 'AI-assisted development improves throughput by shortening the evidence loop: understand the issue, plan, make a bounded change, run automated checks, and present a reviewable result.', lensIntro: 'Automate repeatable proof and preserve human ownership of consequential merges and releases.', example: { situation: 'A team asks Claude to fix bugs directly on the main branch with broad permissions.', tempting: 'Measure success by how many changes Claude produces.', move: 'Use scoped issues, isolated branches or worktrees, project guidance, safe permission defaults, tests and hooks, and human review of the resulting evidence.', why: 'The team gains cycle-time improvement without turning speed into uncontrolled change.' } },
  '7.3': { idea: 'Debugging an AI system means reconstructing the whole execution: input, context, model, retrieval, tools, permissions, environment, and output. Recovery and prevention are separate steps.', lensIntro: 'Start at the first incorrect boundary and use the symptom to route investigation.', example: { situation: 'A tool call works locally but fails in production while Claude supplies correct arguments.', tempting: 'Rewrite the prompt or retry indefinitely.', move: 'Compare environment configuration, credential scope, sandbox and network policy, dependency response, and trace IDs; mitigate safely and add a regression detector.', why: 'The evidence points to the operational boundary, and the durable fix prevents recurrence.' } },
};
